### PR TITLE
issue #57 client certificate generation using sha1 instead of sha256

### PR DESCRIPTION
**Pull request by cookie33**
issue #57 client certificate generation using sha1 instead of sha256 on newer distributions

### CODE REVIEW

**Comment by grnetci** [comment]
Can one of the admins verify this patch?

**Comment by NicolasLiampotis** [comment]
I think the docs should keep suggesting the (default) SHA256-based client certificate generation code and just add a note about using the `-sha1` flag for compatibility reasons, including the following warning:
```
Warning: The use of SHA1 is deprecated and may be disallowed in the future. 
```

**Comment by cookie33** [comment]
CNRI states:

If the key is an RSA key, SHA256 should be supported in Java 7 and up.

If the key is a DSA key, SHA256 should be supported in Java 8 and up.

My system is Centos 6 with Java 7. So an DSA key does NOT support sha256. if we state that an RSA key is to be generated it should work without a problem. Than we can say to use sha256.

**Comment by cookie33** [comment]
Generated private/public keys:
```
      bash /.../handlesystem_software/hsj-8.x.x/bin/hdl-keygen
                    -alg rsa
                    -keysize 4096
                     301_foo_bar_privkey.bin 301_foo_bar_pubkey.bin
```

Generated certificate with `-sha256` and `-subj`
```
        openssl req -pubkey -x509 -new -sha256 -subj "/CN=301:foo\/bar"
                                        -key /.../301_foo_bar_privkey.pem
                                        -out /.../301_certificate_and_publickey.pem
```
Tested. This works on Centos 6 with java version 1.7

**Comment by NicolasLiampotis** [comment]
RSA 4096-long keys for SHA-256 signed certificates seem very sensible (and secure) defaults.

LGTM +1

**Pull request merged**
