### PR TITLE
add setting of prefix parameter to None or value in json config file.

### PR DESCRIPTION
**Pull request by cookie33**
With this change following is achieved;

The json credentials are read from the json file.

If the file contains a key 'prefix' it is set to the prefix.
if the file contains NO key 'prefix' it is set to None.
You can than use the function get_prefix() to get the value.

### CODE REVIEW

**Comment by NicolasLiampotis** [comment]
test this please

**Comment by grnetci** [comment]
Can one of the admins verify this patch?

**Comment by NicolasLiampotis** [comment]
retest this please

**Comment by NicolasLiampotis** [comment]
retest this please

**Comment by NicolasLiampotis** [comment]
retest this please

**Comment by merretbuurman** [comment]
retest this please

**Comment by cookie33** [comment]
retest this please

**Comment by merretbuurman** [comment]
retest this please

**Pull request merged**
