### PR TITLE
Adapted setup.py and setup.cfg.

### PR DESCRIPTION
**Pull request by merretbuurman**
e.g. dependencies, description, and version 0.9.9 with tag ".dev"
When everything is tested and fine, version can be set to 1.0.0 and tag to ".rc" (release candidate)

### CODE REVIEW

**Comment by NicolasLiampotis** [comment]
retest this please

**Comment by NicolasLiampotis** [comment]
retest this please

**Comment by cookie33** [comment]
HI,

The authorization.rst talks about index 300 for the HS_SECKEY.
Then the authorization.rst talks about using index 301 for the HS_PUBKEY.
The example than uses index 300 again for the HS_PUBKEY. This is not consistent. It might look better if  300 is used for the HS_SECKEY and 301 is used for the HS_PUBKEY in the example.

**Comment by TobiasWeigel** [comment]
retest this please

**Comment by merretbuurman** [comment]
Note: As reply to @cookie33 's comment on Feb 16, I have solved that issue in PR #46.

**Comment by NicolasLiampotis** [comment]
retest this please

**Comment by NicolasLiampotis** [comment]
retest this please

**Pull request merged**
