### PR TITLE
Initial implementation of b2handle library

### PR DESCRIPTION
**Pull request by merretbuurman**
Initial implementation of b2handle. Not yet fully covered by unit tests.

### CODE REVIEW

**Comment by NicolasLiampotis** [comment]
test this please

**Comment by NicolasLiampotis** [comment]
test this please

**Comment by merretbuurman** [comment]
test this please

**Comment by NicolasLiampotis** [comment]
jenkins config updated
retest this please

**Comment by NicolasLiampotis** [comment]
retest this please

**Comment by grnetci** [comment]
Can one of the admins verify this patch?

**Comment by NicolasLiampotis** [comment]
test this please

**Comment by NicolasLiampotis** [comment]
retest this please

**Comment by merretbuurman** [comment]
test this please

**Pull request merged**
