### PR TITLE
Https verify can be Boolean or string

### LINKED ISSUE #55: HTTPS_verify could be a string, ca_cert path
Hi!

I want to pass a ca_cert in `HTTPS_verify` so the *requests* library uses It for SSL verification ([documentation](http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification)).

Right now is not possible because boolean is being forced as a type for HTTPS_verify.

```python
Traceback (most recent call last):
  File "epicclient2.py", line 297, in <module>
    _ARGS.func(_ARGS)
  File "epicclient2.py", line 117, in create
    **extra_config)
  File "/usr/lib/python2.7/site-packages/b2handle-1.0-py2.7.egg/b2handle/handleclient.py", line 261, in instantiate_with_credentials
    **additional_config
  File "/usr/lib/python2.7/site-packages/b2handle-1.0-py2.7.egg/b2handle/handleclient.py", line 109, in __init__
    self.__handlesystemconnector = HandleSystemConnector(handleclient=self, **args)
  File "/usr/lib/python2.7/site-packages/b2handle-1.0-py2.7.egg/b2handle/handlesystemconnector.py", line 83, in __init__
    self.__store_args_or_set_to_defaults(args, defaults)
  File "/usr/lib/python2.7/site-packages/b2handle-1.0-py2.7.egg/b2handle/handlesystemconnector.py", line 117, in __store_args_or_set_to_defaults
    self.__HTTPS_verify = util.string_to_bool(args['HTTPS_verify'])
  File "/usr/lib/python2.7/site-packages/b2handle-1.0-py2.7.egg/b2handle/util.py", line 93, in string_to_bool
    return dic[string.lower()]
KeyError: u'ca_cert.crt'
```

### PR DESCRIPTION
**Pull request by javaguirre**
I removed **string_to_bool** function, It was only used for **HTTPS_verify**, I changed It for **get_valid_https_verify** which is more accurate now.

I added unittests for several cases with this method.

I couldn't get all the project unittests working, It would be nice if there could be some documentation on what's necessary for all the tests to pass, I couldn't find It in CONTRIBUTING or README files. The Unittests for the method I added pass (util_test.py).

This should close #55. :-)

### CODE REVIEW

**Comment by grnetci** [comment]
Can one of the admins verify this patch?

**Comment by NicolasLiampotis** [comment]
test this please

**Comment by NicolasLiampotis** [comment]
Thank you Javier for this PR! It's very good that you added unit tests for the extended functionality, however it would be more useful if they were referenced from `main_test_script.py` so that they can be run automatically along with the rest of the unit tests. More information about running B2HNADLE unit tests can be found in the [README](https://github.com/EUDAT-B2SAFE/B2HANDLE/blob/master/b2handle/tests/README.md).

One last thing: I'm in favour of the previous method name (`string_to_bool`) because it's more generic and it will be easier to reuse in the future if an option other than `HTTPS_verify` needs the conversion functionality.

**Comment by javaguirre** [comment]
Hi!

I'll add It to `main_test_script.py`. :-)

The problem with `string_to_bool` is that now is wrong, because is not a string to bool conversion, but It could be also a string returned. It's a very specific functionality and `string_to_bool` was only used for this case and now the case has changed. I'm open to change the name but `string_to_bool` wouldn't be accurate anymore, maybe something like `string_to_bool_or_string` but I don't find It very appealing and this method transformation is very specific to `HTTPS_verify`.

What do you think?

**Comment by javaguirre** [comment]
By the way, It would be nice to have a link from the main README to the test README.

**Comment by NicolasLiampotis** [comment]
> The problem with string_to_bool is that now is wrong, because is not a string to bool conversion, but It could be also a string returned. It's a very specific functionality and string_to_bool was only used for this case and now the case has changed. I'm open to change the name but string_to_bool wouldn't be accurate anymore, maybe something like string_to_bool_or_string but I don't find It very appealing and this method transformation is very specific to HTTPS_verify.

I see your point. I would also expect a `string_to_bool` method to behave like [distutils.util.strtobool](https://docs.python.org/2/distutils/apiref.html#distutils.util.strtobool). On the other hand, if the method is specific to `HTTPS_verify`, why do we include it in a util library intended for common re-usable functions? 
I don't have a strong preference so we might as well leave the new method name.

> By the way, It would be nice to have a link from the main README to the test README.

Good point - will fix that.

One last thing: It would be nice to update the help text for the HTTPS_verify param to make it clear that, besides true/false, a user can pass the path to a CA_BUNDLE file or directory with certificates of trusted CAs

Again, many thanks for the PR.

**Comment by javaguirre** [comment]
> I see your point. I would also expect a string_to_bool method to behave like distutils.util.strtobool. On the other hand, if the method is specific to HTTPS_verify, why do we include it in a util library intended for common re-usable functions? 
I don't have a strong preference so we might as well leave the new method name.

I totally agree with you, I added there the method because It was were the `string_to_bool` method was. I'll check if It makes sense having It somewhere else.

> One last thing: It would be nice to update the help text for the HTTPS_verify param to make it clear that, besides true/false, a user can pass the path to a CA_BUNDLE file or directory with certificates of trusted CAs

Sure!

**Comment by javaguirre** [comment]
Hi!

I added all the changes you suggested, I created a new `utilconfig.py` and moved the tests to `utilconfig_test.py`. I also added the unittests to `main_test_script.py`.

Could you please let me know if everything is good to go?

Thank you!

Note: I didn't squash any commits so It's easier to follow what I did.

**Comment by TobiasWeigel** [comment]
test this please

**Pull request merged**
